# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [ ]:
import numpy as np
arr=np.random.randint(1,20,size=(5,5))
arr

array([[10, 17,  7, 18,  9],
       [ 2,  8, 16,  8,  4],
       [ 6, 11, 10, 15,  1],
       [14, 12,  2,  1,  5],
       [17, 18, 11, 15, 19]], dtype=int32)

In [5]:
arr[:,3]=1
arr

array([[10, 17,  7,  1,  9],
       [ 2,  8, 16,  1,  4],
       [ 6, 11, 10,  1,  1],
       [14, 12,  2,  1,  5],
       [17, 18, 11,  1, 19]], dtype=int32)

In [7]:
arr1=np.random.randint(1,16,size=(4,4))
np.fill_diagonal(arr1,0)
arr1

array([[ 0,  7,  3,  1],
       [14,  0,  2, 11],
       [ 4,  6,  0,  9],
       [ 7, 11, 13,  0]], dtype=int32)

In [12]:
arr2=np.random.randint(1,36,size=(6,6))
print(arr2)
arr2[2:5,1:3]


[[ 9 21 19 19 32 19]
 [24 18 17 22 20 27]
 [16  7 17 14 13 17]
 [10 18 31  7 18 18]
 [ 4 29  8 26 29 22]
 [ 2  3 32 12  9 25]]


array([[ 7, 17],
       [18, 31],
       [29,  8]], dtype=int32)

In [ ]:
arr3=np.random.randint(1,10,size=(5,5))
arr3[]

array([[8, 8, 8, 1, 1],
       [4, 8, 5, 2, 5],
       [3, 8, 7, 5, 1],
       [1, 8, 9, 8, 5]], dtype=int32)