In [3]:
import numpy as np
# 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [2]:
!pip install numpy


   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   ------ --------------------------------- 2.1/12.8 MB 6.5 MB/s eta 0:00:02
   ------- -------------------------------- 2.4/12.8 MB 6.4 MB/s eta 0:00:02
   -------- ------------------------------- 2.6/12.8 MB 3.1 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.8 MB 3.1 MB/s eta 0:00:04
   --------- ------------------------------ 3.1/12.8 MB 2.4 MB/s eta 0:00:05
   ---------- ----------------------------- 3.4/12.8 MB 1.9 MB/s eta 0:00:05
   ----------- ---------------------------- 3.7/12.8 MB 1.8 MB/s eta 0:00:05
   ------------ --------------------------- 3.9/12.8 MB 1.8 MB/s eta 0:00:05
   ------------- -------------------------- 4.5/12.8 MB 1.8 MB/s eta 0:00:05
   -------------- ------------------------- 4.7/12.8 MB 1.8 MB/s eta 0:00:05
   ----------------- ---------------------- 5.5/12.8 MB 1.9 MB/s eta 0:00:04
   ----------

In [5]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [8]:
arr3=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr3.shape


(2, 5)

In [ ]:
np.arrange(0,10,2)

In [11]:
#Vectorized operations using numpy
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#Element wise additon
print(arr1+arr2)
#subtraction
print(arr2-arr1)
#multiplication
print(arr1*arr2)
#division
print(arr2/arr1)


[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [ ]:
#Universal funtions
arr1=np.array([2,3,4,5,6])
#square root
print(np.sqrt(arr1))
#Exponential
print(np.exp(arr1))
#sine
print(np.sin(arr1))
#Natural log
print(np.log(arr1))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [25]:
#Array slicing and indexing
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr1)

arr1[0][2]
arr1[2:]
print(arr1[1:,2:])
print(arr1[1:,1:3])



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]


In [26]:
#Modify array elements
arr1[0][0]=100
print(arr1)


[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [27]:
#Statistical concept-Normalization
#Change my data to have a mean of zero and standard deviationof 1

data=np.array([1,2,3,4,5])
#Mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)

#Normalize the data
normalized_data=(data-mean)/std_dev
print(normalized_data)


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [30]:
#Logical opertions
data=np.array(([1,2,3,4,5,6,7,8,9,10]))
data[data>5]

array([ 6,  7,  8,  9, 10])